r = require "rethinkdb"
randomstring = require "randomstring"

module.exports = (robot) ->
    robot.logger.error "connecting to rethinkdb"
    r.connect
        host: process.env.RETHINKDB_PORT_28015_TCP_ADDR and process.env.RETHINKDB_PORT_28015_TCP_ADDR or "127.0.0.1"
        port: 28015
        authKey: process.env.RETHINKDB_AUTHKEY and process.env.RETHINKDB_AUTHKEY or null
    , (error, conn) ->
        if error
            robot.logger.error error
            return

        verify = (msg) ->
            id = randomstring.generate 20
            date = new Date()

            db = "dev"
            if msg.match[2]
                db = msg.match[2]

            r.db(db).table("accounts").filter({"name": msg.match[1]}).run conn, (error, cursor) ->
                if error
                    msg.reply "Database error: " + error
                    return

                cursor.toArray (error, accounts) ->
                    if accounts.length isnt 1
                        msg.reply "User not found: " + msg.match[1]
                        return

                    token =
                        id: id
                        date_created: date
                        date_modified: date
                        expiry_date: new Date(+new Date + 12096e5)
                        name: "Verification token generated by Lavabroom"
                        type: "verify"
                        owner: accounts[0].id


                    r.db(db).table("tokens").insert(token).run conn, (error, result) ->
                        if error
                            msg.reply "Database error: " + error
                            return

                        msg.reply "New verification token: " + id
                        return

        robot.respond /verify (\w*)$/i, verify
        robot.respond /verify (\w*) in (\w*)$/i, verify
